### ISSUE TITLE
Steel smeltry recipe missing

### ISSUE THREAD

**Issue by pwnage-pineapple** [TheOldOne822/SimpleTcon#1]
I was unable to find the recipe for Steel using the TiC smeltery. JEI also listed no alloying recipe for Steel

**Comment by TheOldOne822** [comment]
TiC never had a Steel recipe of its own and I didn't see a good way to make one within the smeltery.
Simple Ores fusion furnace hasn't ported the old 1.7.10 NEI recipe handler to JEI yet but there is a fusion furnace recipe for steel.
