### ISSUE TITLE
Crash w/ TAIGA Mod

### ISSUE THREAD

**Issue by WenXin20** [TheOldOne822/SimpleTcon#2]
Forge 1.10.2-2116
Simple Tcon v1.0
[TAIGA v1.1.4](https://minecraft.curseforge.com/projects/taiga-tinkers-alloying-addon)
This mod adds Mythril to the Tcon smeltery as well, which seems to be causing a crash.
[Crash Report](http://pastebin.com/U63zf8v0)

**Comment by TheOldOne822** [comment]
Mythril is a common ore name and unfortunately TiC crashes if two mods try to use the same name for adding materials. I'll see if I can make a functional workaround but a proper fix would need to be done in TiC itself and unfortunately would likely require changing of much of the TiC code.

**Comment by WenXin20** [comment]
Ok, thanks

**Comment by P3rf3ctXZer0** [comment]
MythX would be start I can confirm this bug sucks.

**Comment by P3rf3ctXZer0** [comment]
Or Mythrilia.
